import { ReactNode } from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import { Activity, CalendarDays, ClipboardList, FileText, LayoutDashboard, LogOut, Pill, ShieldCheck, Stethoscope, Users, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

const links = [['/', 'Dashboard', LayoutDashboard], ['/patients', 'Patients', Users], ['/appointments', 'Appointments', CalendarDays], ['/doctors', 'Doctors', UserRound], ['/medical-records', 'Medical records', Stethoscope], ['/laboratory', 'Laboratory', ClipboardList], ['/pharmacy', 'Pharmacy', Pill], ['/billing', 'Billing', FileText]] as const;
export function DashboardLayout({ children }: { children: ReactNode }) {
  const { user, logout } = useAuth(); const navigate = useNavigate();
  const visibleLinks = user?.role === 'Admin' ? [...links, ['/users', 'User management', ShieldCheck] as const] : links;
  return <div className="flex min-h-screen bg-slate-50 text-ink"><aside className="hidden w-64 shrink-0 bg-ink p-5 text-white md:block"><div className="mb-10 flex items-center gap-2 px-2"><span className="rounded-xl bg-primary p-2"><Activity size={20}/></span><span className="text-lg font-bold">CarePoint</span></div><nav className="space-y-1">{visibleLinks.map(([to, label, Icon]) => <NavLink key={to} to={to} data-testid={`nav-${label.toLowerCase().replace(/ /g, '-')}`} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${isActive ? 'bg-white/15 text-white' : 'text-slate-400 hover:bg-white/10 hover:text-white'}`}><Icon size={18}/>{label}</NavLink>)}</nav><button data-testid="logout-button" onClick={() => { logout(); navigate('/login'); }} className="mt-12 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-slate-400 hover:bg-white/10 hover:text-white"><LogOut size={18}/>Sign out</button></aside><main className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4 md:px-8"><div><p className="text-sm text-slate-500">Good morning,</p><h1 data-testid="user-name" className="text-lg font-bold">{user?.firstName} {user?.lastName}</h1></div><div className="flex items-center gap-3"><span data-testid="user-role" className="hidden rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-primary sm:block">{user?.role}</span><div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary font-bold text-white">{user?.firstName?.[0]}</div></div></header><div className="p-5 md:p-8">{children}</div></main></div>;
}
