import { useEffect, useState } from 'react';
import { CalendarDays, ClipboardList, IndianRupee, Users } from 'lucide-react';
import { StatCard } from '../components/StatCard';
import { api } from '../services/api';
import { DashboardStats } from '../types';
export function Dashboard() {
  const [stats, setStats] = useState<DashboardStats>({ patients: 0, appointments: 0, revenue: 0, labTests: 0, medicines: 0, staff: 0 });
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.get('/reports/dashboard').then(({ data }) => setStats(data.data)).catch(() => undefined).finally(() => setLoading(false)); }, []);
  return <div><div className="mb-8"><p className="text-sm font-medium text-primary">Overview</p><h2 data-testid="dashboard-title" className="mt-1 text-3xl font-bold">Hospital dashboard</h2><p className="mt-2 text-slate-500">Monitor today’s operations at a glance.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{loading ? [1,2,3,4].map(i => <div key={i} className="h-36 animate-pulse rounded-2xl bg-slate-200"/>) : <><StatCard label="Total patients" testId="patients" value={stats.patients} icon={<Users size={20}/>} /><StatCard label="Appointments" testId="appointments" value={stats.appointments} icon={<CalendarDays size={20}/>} tone="green"/><StatCard label="Revenue" testId="revenue" value={`₹${stats.revenue.toLocaleString()}`} icon={<IndianRupee size={20}/>} tone="purple"/><StatCard label="Lab tests" testId="lab-tests" value={stats.labTests} icon={<ClipboardList size={20}/>} tone="orange"/></>}</div><div className="mt-8 grid gap-5 lg:grid-cols-3"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-100 lg:col-span-2"><h3 className="font-bold">Operational summary</h3><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4">{[['Medicines',stats.medicines],['Staff',stats.staff],['Lab tests',stats.labTests],['Appointments',stats.appointments]].map(([label,value]) => <div key={label as string} data-testid={`summary-${(label as string).toLowerCase().replace(' ', '-')}`} className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p data-testid={`summary-${(label as string).toLowerCase().replace(' ', '-')}-value`} className="mt-2 text-xl font-bold">{value}</p></div>)}</div></div><div className="rounded-2xl bg-ink p-6 text-white"><h3 className="font-bold">Care team status</h3><p className="mt-2 text-sm text-slate-400">Keep your teams aligned with real-time updates.</p><div className="mt-8 flex items-center gap-3"><span className="h-3 w-3 rounded-full bg-emerald-400"/><span className="text-sm">All systems operational</span></div></div></div></div>;
}
