import { FormEvent, useState } from 'react';
import { Activity, LockKeyhole, Mail } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { Link } from 'react-router-dom';
export function Login() {
  const { login } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await login(email, password); navigate('/'); } catch (e: any) { setError(e.response?.data?.message || 'Unable to sign in'); } finally { setBusy(false); } };
  return <div className="flex min-h-screen items-center justify-center bg-slate-100 p-5"><div className="grid w-full max-w-4xl overflow-hidden rounded-3xl bg-white shadow-xl md:grid-cols-2"><div className="hidden bg-ink p-10 text-white md:block"><div className="flex items-center gap-2"><Activity className="text-blue-400"/><span className="text-xl font-bold">CarePoint</span></div><h1 className="mt-24 text-4xl font-bold leading-tight">Better care begins with a connected team.</h1><p className="mt-5 text-slate-400">Securely manage patients, appointments, clinical records, and hospital operations.</p></div><form onSubmit={submit} data-testid="login-form" className="p-8 md:p-12"><h2 className="text-2xl font-bold">Welcome back</h2><p className="mt-2 text-sm text-slate-500">Sign in to your workspace</p>{error && <div role="alert" data-testid="login-error" className="mt-6 rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</div>}<label className="mt-8 block text-sm font-medium">Email<input required type="email" name="email" data-testid="login-email" value={email} onChange={e => setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-primary" placeholder="you@hospital.com"/></label><label className="mt-5 block text-sm font-medium">Password<div className="relative"><LockKeyhole size={17} className="absolute left-3 top-3.5 text-slate-400"/><input required type="password" name="password" data-testid="login-password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 py-3 pl-10 pr-4 outline-none focus:border-primary"/></div></label><button type="submit" data-testid="login-submit" disabled={busy} className="mt-8 w-full rounded-xl bg-primary py-3 font-semibold text-white hover:bg-blue-700 disabled:opacity-60">{busy ? 'Signing in...' : 'Sign in'}</button><p className="mt-5 text-center text-sm text-slate-500">Need an account? <Link to="/register" className="font-semibold text-primary hover:underline">Create one</Link></p></form></div></div>;
}
